"use client";
export const genres = [
  { id: 10759, value: "action", name: "Action" },
  { id: 10759, value: "adventure", name: "Adventure" },
  { id: 16, value: "animation", name: "Animation" },
  { id: 35, value: "comedy", name: "Comedy" },
  { id: 80, value: "crime", name: "Crime" },
  { id: 99, value: "documentary", name: "Documentary" },
  { id: 18, value: "drama", name: "Drama" },
  { id: 10751, value: "family", name: "Family" },
  { id: 10765, value: "fantasy", name: "Fantasy" },
  { id: 36, value: "history", name: "History" },
  { id: 27, value: "horror", name: "Horror" },
  { id: 10402, value: "music", name: "Music" },
  { id: 9648, value: "mystery", name: "Mystery" },
  { id: 10749, value: "romance", name: "Romance" },
  { id: 878, value: "sci-fi", name: "Sci-Fi" },
  { id: 53, value: "thriller", name: "Thriller" },
  { id: 10752, value: "war", name: "War" },
  { id: 37, value: "western", name: "Western" },
];
export const sortMovies = [
  { value: "popularity_desc", name: "Popularity Descending" },
  { value: "popularity_asc", name: "Popularity Ascending" },
  { value: "rating_desc", name: "Rating Descending" },
  { value: "rating_asc", name: "Rating Ascending" },
  { value: "release_desc", name: "Release Date Descending" },
  { value: "release_asc", name: "Release Date Ascending" },
  { value: "title_asc", name: "Title (A-Z)" },
];
export const genres2 = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
};
